version: "3"

tasks:
  build:
    aliases:
      - build
    desc: "build projects"
    cmds:
      - go build -o bin/fily src/cmd/*.go

  run:
    aliases:
      - run 
    desc: "runs programs"
    cmds:
      - task build
      - ./bin/fily 

  test:
    aliases:
     - test
    desc: "run tests"
    cmds:
      - go test -v ./internal/app/...
