env: "local" # dev, prod

database:
  ip:       "127.0.0.1"
  port:     "5432"
  user:     "postgres"
  password: "postgres"
  sslMode:  "disable"
  dbName:   "fily"


web:
  ip:       "127.0.0.1"
  port:     "8080"
  

